//! Runs the filters against a real KITTI raw sequence (2011_09_26_drive_0005,
//! oxts channel only: https://www.cvlibs.net/datasets/kitti/raw_data.php) and
//! reports RMSE against ground truth, plus speed -- same shape of comparison
//! as `imu_bench.zig`, different dataset and problem structure.
//!
//! KITTI's oxts output (from an OXTS RT3003 GPS/INS unit) is treated as
//! ground truth position/heading/speed. The benchmark dataset
//! (`src/data/kitti_gps_imu.txt`, generated by a script kept alongside this
//! repo's history) adds synthetic Gaussian position noise (fixed seed,
//! std=2m, typical consumer GPS accuracy) on top of the true trajectory to
//! simulate a GPS receiver; the real forward-acceleration (`af`) and yaw-rate
//! (`wu`) channels are used unmodified as IMU control inputs.
//!
//! `kalman.KalmanFilter` never touches the IMU signals at all -- constant
//! velocity in (vx, vy), corrected by noisy GPS position only, same
//! structure as `imu_bench.zig`'s linear filter.
//!
//! `extended_kalman.ExtendedKalmanFilter` with `gps_ins.GpsModel` is a real
//! IMU-driven bicycle model: state [px, py, v, yaw], propagated using the
//! actual accelerometer/gyro readings as control inputs each step, corrected
//! by the same noisy GPS position.

const std = @import("std");
const builtin = @import("builtin");
const Io = std.Io;
const Purifier = @import("Purifier");
const kalman = Purifier.kalman;
const extended_kalman = Purifier.extended_kalman;
const iterated_extended_kalman = Purifier.iterated_extended_kalman;
const unscented_kalman = Purifier.unscented_kalman;
const square_root_kalman = Purifier.square_root_kalman;
const gps_ins = @import("gps_ins.zig");
const cv = @import("constant_velocity.zig");
const maryam = @import("maryam");
const bench_common = @import("bench_common.zig");
const BenchResult = bench_common.BenchResult;
const ErrorAccumulator = bench_common.ErrorAccumulator;
const report = bench_common.report;

const data = @embedFile("data/kitti_gps_imu.txt");

const gps_noise_var = 4.0; // (2m std)^2, matches the dataset generator

// ---- Linear KF: constant-velocity model, GPS only, no IMU ----

const KF = kalman.KalmanFilter(4, 1, 2);

fn runLinear(io: Io) !BenchResult {
    var filter: KF = undefined;
    var initialized = false;
    var prev_t: f64 = 0;
    var acc = ErrorAccumulator{};

    var lines = std.mem.tokenizeScalar(u8, data, '\n');
    while (lines.next()) |line_raw| {
        const line = std.mem.trimEnd(u8, line_raw, "\r");
        if (line.len == 0) continue;

        var fields = std.mem.tokenizeScalar(u8, line, '\t');
        const t = try std.fmt.parseFloat(f64, fields.next().?);
        const gps_px = try std.fmt.parseFloat(f64, fields.next().?);
        const gps_py = try std.fmt.parseFloat(f64, fields.next().?);
        _ = fields.next(); // af (unused by this filter)
        _ = fields.next(); // wu (unused by this filter)
        const gt_px = try std.fmt.parseFloat(f64, fields.next().?);
        const gt_py = try std.fmt.parseFloat(f64, fields.next().?);
        const gt_v = try std.fmt.parseFloat(f64, fields.next().?);
        const gt_yaw = try std.fmt.parseFloat(f64, fields.next().?);

        if (!initialized) {
            filter = .{
                .x = blk: {
                    var m = cv.StateVec.zero();
                    m.data = .{ .{gps_px}, .{gps_py}, .{0}, .{0} };
                    break :blk m;
                },
                .P = blk: {
                    var m = cv.StateMat.zero();
                    m.data[0][0] = 1;
                    m.data[1][1] = 1;
                    m.data[2][2] = 1000;
                    m.data[3][3] = 1000;
                    break :blk m;
                },
                .F = cv.identity(),
                .B = cv.ControlMat.zero(),
                .Q = cv.StateMat.zero(),
                .H = cv.measureH(),
                .R = blk: {
                    var m = cv.MeasureNoise.zero();
                    m.data[0][0] = gps_noise_var;
                    m.data[1][1] = gps_noise_var;
                    break :blk m;
                },
            };
            prev_t = t;
            initialized = true;
            continue;
        }

        const dt = t - prev_t;
        prev_t = t;

        filter.F = cv.stateTransition(dt);
        filter.Q = cv.processNoise(dt, 9.0, 9.0);

        const t0 = Io.Timestamp.now(io, .awake);
        filter.predict(cv.ControlVec.zero());

        var z = cv.MeasureVec.zero();
        z.data = .{ .{gps_px}, .{gps_py} };
        const update_result = filter.update(z);
        const t1 = Io.Timestamp.now(io, .awake);
        acc.filter_ns += t0.durationTo(t1).nanoseconds;
        update_result catch {
            acc.recordSingular();
            continue;
        };

        const gt_vx = gt_v * @cos(gt_yaw);
        const gt_vy = gt_v * @sin(gt_yaw);
        acc.record(.{
            filter.x.data[0][0] - gt_px,
            filter.x.data[1][0] - gt_py,
            filter.x.data[2][0] - gt_vx,
            filter.x.data[3][0] - gt_vy,
        });
    }

    return acc.finish(@sizeOf(KF));
}

// ---- Bicycle EKF/UKF/SR-KF: IMU-driven (real af/wu control inputs), GPS correction ----

const BicycleEKF = extended_kalman.ExtendedKalmanFilter(4, 3, 2, gps_ins.GpsModel);

// Reuses gps_ins.GpsModel unchanged for the IEKF, UKF, and SR-KF -- same
// reasoning as imu_bench.zig's LidarUKF/RadarUKF/LidarSRKF/RadarSRKF.
const BicycleIEKF = iterated_extended_kalman.IteratedExtendedKalmanFilter(4, 3, 2, gps_ins.GpsModel, 3);
const BicycleUKF = unscented_kalman.UnscentedKalmanFilter(4, 3, 2, gps_ins.GpsModel);
const BicycleSRKF = square_root_kalman.SquareRootKalmanFilter(4, 3, 2, gps_ins.GpsModel);

// Same values used to independently validate this model against filterpy
// (see maryam_fix.md / Readme.md for how that comparison was produced) --
// left exactly as originally chosen so that validation stays reproducible.
const ekf_std_af_untuned = 1.0; // process-noise std for the accel input, m/s^2
const ekf_std_wu_untuned = 0.2; // process-noise std for the yaw-rate input, rad/s

// A different Q, found with a coarse grid search over this exact dataset
// (see git history for the sweep) minimizing summed RMSE across
// px/py/vx/vy. The change here is much smaller than the CTRV filter's (see
// Readme.md) -- consistent with this being a short, real, noisy sequence
// rather than a long synthetic one.
const ekf_std_af_alt = 0.15;
const ekf_std_wu_alt = 0.03;

// Shared by the EKF, IEKF, UKF, and SR-KF configurations below: only the
// filter type (`Filter`) and initial v/yaw covariance differ, everything
// else -- dataset parsing, dt/Q computation, error accumulation -- is
// identical. `bench_common.predictErr` absorbs one structural difference
// (EKF's and IEKF's predict() can't fail; UKF's and SR-KF's can), and
// `bench_common.makeFilter`/`covOf` absorb another (SR-KF's field is `L`,
// not `P`). IEKF needs no changes here at all -- same `predict()`/`update()`
// signatures as the plain EKF.
//
// `initial_vyaw_cov` exists because the "right" initial value is NOT the
// same number for every filter, unlike everywhere else in this codebase
// where P's exact magnitude doesn't matter as long as it's "wide":
//   - EKF/linear/IEKF use P purely algebraically, so P[2][2]=P[3][3]=1000
//     (no prior belief about v/yaw) is harmless -- IEKF re-linearizes H at
//     better state estimates, but never samples a point far from the mean
//     the way the UKF does, so it has no analogous sensitivity.
//   - UKF's sigma points are genuinely sampled at mean +- sqrt(n+lambda)*
//     sigma, and sqrt(1000)*spread(~2) is ~63 -- for `yaw`, a periodic
//     quantity, 63 radians wraps around 2*pi about ten times, landing sigma
//     points at essentially arbitrary phases. Found by comparing the UKF's
//     first (broken, RMSE in the single digits) results against the EKF's;
//     the fix is passing 1 instead of 1000 for the UKF, confirmed correct
//     via the filterpy exact-match documented in Readme.md.
//   - SR-KF is algebraically identical to the EKF (see
//     square_root_kalman.zig), so it wants the *same* P=1000 the EKF gets
//     -- but SR-KF's field holds P's Cholesky factor, not P, so the value
//     passed for it is `@sqrt(1000)`, not `1000`.
fn runBicyclePair(comptime Filter: type, io: Io, std_af: f64, std_wu: f64, initial_vyaw_cov: f64) !BenchResult {
    var x = gps_ins.StateVec.zero();
    var cov = maryam.I(4);
    var initialized = false;
    var prev_t: f64 = 0;
    var acc = ErrorAccumulator{};

    var lines = std.mem.tokenizeScalar(u8, data, '\n');
    while (lines.next()) |line_raw| {
        const line = std.mem.trimEnd(u8, line_raw, "\r");
        if (line.len == 0) continue;

        var fields = std.mem.tokenizeScalar(u8, line, '\t');
        const t = try std.fmt.parseFloat(f64, fields.next().?);
        const gps_px = try std.fmt.parseFloat(f64, fields.next().?);
        const gps_py = try std.fmt.parseFloat(f64, fields.next().?);
        const af = try std.fmt.parseFloat(f64, fields.next().?);
        const wu = try std.fmt.parseFloat(f64, fields.next().?);
        const gt_px = try std.fmt.parseFloat(f64, fields.next().?);
        const gt_py = try std.fmt.parseFloat(f64, fields.next().?);
        const gt_v = try std.fmt.parseFloat(f64, fields.next().?);
        const gt_yaw = try std.fmt.parseFloat(f64, fields.next().?);

        if (!initialized) {
            x.data[0][0] = gps_px;
            x.data[1][0] = gps_py;
            cov = blk: {
                var m = gps_ins.StateMat.zero();
                m.data[0][0] = 1;
                m.data[1][1] = 1;
                m.data[2][2] = initial_vyaw_cov;
                m.data[3][3] = initial_vyaw_cov;
                break :blk m;
            };
            prev_t = t;
            initialized = true;
            continue;
        }

        const dt = t - prev_t;
        prev_t = t;

        const Q = gps_ins.processNoise(dt, std_af, std_wu);
        var u = gps_ins.ControlVec.zero();
        u.data = .{ .{af}, .{wu}, .{dt} };

        const t0 = Io.Timestamp.now(io, .awake);
        var filt = bench_common.makeFilter(Filter, x, cov, Q, blk: {
            var m = gps_ins.GpsNoise.zero();
            m.data[0][0] = gps_noise_var;
            m.data[1][1] = gps_noise_var;
            break :blk m;
        });
        var update_err = bench_common.predictErr(&filt, u);
        if (update_err == null) {
            var z = gps_ins.GpsVec.zero();
            z.data = .{ .{gps_px}, .{gps_py} };
            filt.update(z) catch |e| {
                update_err = e;
            };
        }
        const t1 = Io.Timestamp.now(io, .awake);
        acc.filter_ns += t0.durationTo(t1).nanoseconds;
        x = filt.x;
        cov = bench_common.covOf(gps_ins.StateMat, filt);

        if (update_err != null) {
            acc.recordSingular();
            continue;
        }

        const est_vx = x.data[2][0] * @cos(x.data[3][0]);
        const est_vy = x.data[2][0] * @sin(x.data[3][0]);
        const gt_vx = gt_v * @cos(gt_yaw);
        const gt_vy = gt_v * @sin(gt_yaw);
        acc.record(.{
            x.data[0][0] - gt_px,
            x.data[1][0] - gt_py,
            est_vx - gt_vx,
            est_vy - gt_vy,
        });
    }

    return acc.finish(@sizeOf(Filter));
}

pub fn run(w: *Io.Writer, io: Io) !void {
    const linear = try runLinear(io);
    const bicycle_untuned = try runBicyclePair(BicycleEKF, io, ekf_std_af_untuned, ekf_std_wu_untuned, 1000);
    const bicycle_alt = try runBicyclePair(BicycleEKF, io, ekf_std_af_alt, ekf_std_wu_alt, 1000);
    const bicycle_iekf = try runBicyclePair(BicycleIEKF, io, ekf_std_af_untuned, ekf_std_wu_untuned, 1000);
    const bicycle_ukf = try runBicyclePair(BicycleUKF, io, ekf_std_af_untuned, ekf_std_wu_untuned, 1);
    const bicycle_srkf = try runBicyclePair(BicycleSRKF, io, ekf_std_af_untuned, ekf_std_wu_untuned, @sqrt(1000.0));

    try w.print("dataset: KITTI 2011_09_26_drive_0005 (real vehicle trajectory, 154 frames @ ~9.6Hz)\n\n", .{});
    try report(w, "Linear KF -- constant-velocity model, GPS only (no IMU)", linear);
    try report(w, "Bicycle EKF (untuned Q) -- IMU-driven, GPS correction", bicycle_untuned);
    try report(w, "Bicycle EKF (different Q) -- IMU-driven, GPS correction", bicycle_alt);
    try report(w, "Bicycle IEKF, max 3 iterations (same Q as untuned EKF) -- IMU-driven, GPS correction", bicycle_iekf);
    try report(w, "Bicycle UKF (same Q as untuned EKF) -- IMU-driven, GPS correction", bicycle_ukf);
    try report(w, "Bicycle SR-KF (same Q as untuned EKF) -- IMU-driven, GPS correction", bicycle_srkf);

    try w.print("-- comparison: linear -> EKF untuned -> EKF different Q -> IEKF -> UKF -> SR-KF --\n", .{});
    try w.print("RMSE px  {d:.4} -> {d:.4} -> {d:.4} -> {d:.4} -> {d:.4} -> {d:.4}\n", .{ linear.rmse[0], bicycle_untuned.rmse[0], bicycle_alt.rmse[0], bicycle_iekf.rmse[0], bicycle_ukf.rmse[0], bicycle_srkf.rmse[0] });
    try w.print("RMSE py  {d:.4} -> {d:.4} -> {d:.4} -> {d:.4} -> {d:.4} -> {d:.4}\n", .{ linear.rmse[1], bicycle_untuned.rmse[1], bicycle_alt.rmse[1], bicycle_iekf.rmse[1], bicycle_ukf.rmse[1], bicycle_srkf.rmse[1] });
    try w.print("RMSE vx  {d:.4} -> {d:.4} -> {d:.4} -> {d:.4} -> {d:.4} -> {d:.4}\n", .{ linear.rmse[2], bicycle_untuned.rmse[2], bicycle_alt.rmse[2], bicycle_iekf.rmse[2], bicycle_ukf.rmse[2], bicycle_srkf.rmse[2] });
    try w.print("RMSE vy  {d:.4} -> {d:.4} -> {d:.4} -> {d:.4} -> {d:.4} -> {d:.4}\n", .{ linear.rmse[3], bicycle_untuned.rmse[3], bicycle_alt.rmse[3], bicycle_iekf.rmse[3], bicycle_ukf.rmse[3], bicycle_srkf.rmse[3] });

    if (builtin.os.tag != .windows) {
        const ru = std.posix.getrusage(std.posix.rusage.SELF);
        const peak_kb: i64 = if (builtin.os.tag == .macos) @divTrunc(ru.maxrss, 1024) else ru.maxrss;
        try w.print("\nprocess peak RSS = {d} KB (whole program, all six filters + both benchmarks)\n", .{peak_kb});
    }

    try w.flush();
}
